const produtos = {
 petshop: [
  { id: 'p1', name: 'RACAO DOG CHOW ADULTO PEQUENOS KG', price: '210', image: '../../assets/produtos/carrinho.png' },
  { id: 'p2', name: 'RACAO MAGNUS CHIPS CARNE FRANGO KG', price: '139', image: '../../assets/produtos/carrinho.png' },
  { id: 'p3', name: 'RACAO TRATTO PREMIUM ADULTO CARNE/CEREAIS KG', price: '125', image: '../../assets/produtos/carrinho.png' },
  { id: 'p4', name: 'RACAO TRATTO PREMIUM FILHOTE CARNE KG', price: '139', image: '../../assets/produtos/carrinho.png' },
  { id: 'p5', name: 'RACAO CHANIN FILHOTE KG', price: '199', image: '../../assets/produtos/carrinho.png' },
  { id: 'p6', name: 'RACAO CHANIN CASTRADOS KG', price: '199', image: '../../assets/produtos/carrinho.png' },
  { id: 'p7', name: 'RACAO CHANIN S/COR CAT MIX KG', price: '179', image: '../../assets/produtos/carrinho.png' },
  { id: 'p8', name: 'AREIA HIGIENICA GRIFFE CAT', price: '4', image: '../../assets/produtos/carrinho.png' },
  { id: 'p9', name: 'AREIA HIGIENICA PERF ADG FLORAL', price: '6', image: '../../assets/produtos/carrinho.png' },
  { id: 'p10', name: 'WHISKAS SACHE ADULTO JELLY PEIXE 85G', price: '2', image: '../../assets/produtos/carrinho.png' },
  { id: 'p11', name: 'PEDIGREE SACHE ADULTO RACA PEQUENA CARNE 100G', price: '2', image: '../../assets/produtos/carrinho.png' },
  { id: 'p12', name: 'PEDIGREE SACHE ADULTO RACA PEQUENA FRANGO 100G', price: '2', image: '../../assets/produtos/carrinho.png' },
  { id: 'p13', name: 'WHISKAS SACHE ADULTO FRANGO/MOLHO 85G', price: '2', image: '../../assets/produtos/carrinho.png' },
  { id: 'p14', name: 'RACAO WHISKAS PEIXE C/DELICROC KG', price: '117', image: '../../assets/produtos/carrinho.png' },
],
mercearia: [
  { id: 'm1', name: 'ACETONA ALYNE 100ML', price: '1', image: '../../assets/produtos/Acetona.png' },
  { id: 'm2', name: 'ABS INTIMUS GEL NOTURNO SUAVE C/ABAS C/8', price: '1', image: '../../assets/produtos/Intimus noturno.png' },
  { id: 'm3', name: 'ABS INTIMUS GEL TRIPLA SUAVE C/ABAS C/8', price: '1', image: '../../assets/produtos/Intimus suave c abas.png' },
  { id: 'm4', name: 'ABS INTIMUS GEL TRIPLA SUAVE S/ABAS C/8', price: '1', image: '../../assets/produtos/Intimus suave s abas.png' },
  { id: 'm5', name: 'ADOCANTE ZERO-CAL 100ML', price: '1', image: '../../assets/produtos/adocante.png' },
  { id: 'm6', name: 'AGUA MINERAL INDAIA 500ML C/GAS', price: '3', image: '../../assets/produtos/Agua c gas.png' },
  { id: 'm7', name: 'AGUA MINERAL INDAIA 500ML S/GAS', price: '3', image: '../../assets/produtos/agua s gas.png' },
  { id: 'm8', name: 'AGUA SANITARIA BRILUX MULTI PROMO 1L', price: '1', image: '../../assets/produtos/brilux.png' },
  { id: 'm9', name: 'AGUA SANITARIA DRAGAO 1L', price: '1', image: '../../assets/produtos/dragao.png' },
  { id: 'm10', name: 'ALCOOL LIQUIDO SANTA CRUZ 70% 1L', price: '1', image: '../../assets/produtos/alcool.png' },
  { id: 'm11', name: 'ALGODAO NEVOA 25G', price: '1', image: '../../assets/produtos/algodao.png' },
  { id: 'm12', name: 'ALHO ROXO IMPORTADO KG', price: '1', image: '../../assets/produtos/alho.png' },
  { id: 'm13', name: 'AMACIANTE DOWNY 500ML BRISA INTENSA PROMO', price: '1', image: '../../assets/produtos/downy intenso.png' },
  { id: 'm14', name: 'AMACIANTE DOWNY 500ML BRISA VERAO PROMO', price: '1', image: '../../assets/produtos/downy brisa.png' },
  { id: 'm15', name: 'AMACIANTE DOWNY 500ML LIRIOS DO CAMPO', price: '1', image: '../../assets/produtos/downy lirios.png' },
  { id: 'm16', name: 'AMACIANTE SONHO 2L MAGIC PROMO', price: '2', image: '../../assets/produtos/sonho magic.png' },
  { id: 'm17', name: 'AMACIANTE SONHO 500ML MAGIC', price: '1', image: '../../assets/produtos/sonho magic 500.png' },
  { id: 'm18', name: 'AMACIANTE YPE 2L ACONCHEGO AZUL', price: '2', image: '../../assets/produtos/ype 2L.png' },
  { id: 'm19', name: 'APARELHO GILLETTE PRESTOBARBA', price: '1', image: '../../assets/produtos/gillete.png' },
  { id: 'm20', name: 'ARROZ 101 BRANCO 1KG', price: '2', image: '../../assets/produtos/101 branco.png' },
  { id: 'm21', name: 'ARROZ 101 PARBOILIZADO 1KG', price: '2', image: '../../assets/produtos/101 parbolizado.png' },
  { id: 'm22', name: 'ARROZ ITAGUARY BRANCO 1KG', price: '2', image: '../../assets/produtos/carrinho.png' },
  { id: 'm23', name: 'ARROZ ITAGUARY PARBOILIZADO 1KG', price: '2', image: '../../assets/produtos/itaguary parbolizado.png' },
  { id: 'm24', name: 'AVEIA QUAKER FLOCOS FINOS 165G', price: '1', image: '../../assets/produtos/aveia flocos finos.png' },
  { id: 'm25', name: 'AVEIA QUAKER FLOCOS REGULAR 165G', price: '1', image: '../../assets/produtos/aveia flocos regular.png' },
  { id: 'm26', name: 'TAMPICO 330ML', price: '1', image: '../../assets/produtos/tampico 330ml.png' },
  { id: 'm27', name: 'BISC CREAM CRACKER FORTALEZA 350G', price: '1', image: '../../assets/produtos/cream cracker.png' },
  { id: 'm28', name: 'BISC FORTALEZA MAIZENA 350G', price: '1', image: '../../assets/produtos/bisc maizena.png' },
  { id: 'm29', name: 'BISC FORTALEZA POP SALGADA 400G', price: '1', image: '../../assets/produtos/cracker mini.png' },
  { id: 'm30', name: 'BISC PIRAQUE MALTADO COBERTO 80G', price: '1', image: '../../assets/produtos/piraque maltado.png' },
  { id: 'm31', name: 'BISC RECHEADO ANIMADOS QUADRADO 130G CHOCOLATE', price: '1', image: '../../assets/produtos/animados choc.png' },
  { id: 'm32', name: 'BISC RECHEADO ANIMADOS QUADRADO 130G MORANGO', price: '1', image: '../../assets/produtos/animados moran.png' },
  { id: 'm33', name: 'BISC RECHEADO RICHESTER AMORI 125G PACK CHOCOLATE', price: '1', image: '../../assets/produtos/amori choc.png' },
  { id: 'm34', name: 'BISC RECHEADO RICHESTER AMORI 125G PACK ESCURO', price: '1', image: '../../assets/produtos/escureto.png' },
  { id: 'm35', name: 'BISC RECHEADO RICHESTER AMORI 125G PACK MORANGO', price: '1', image: '../../assets/produtos/amori morango.png' },
  { id: 'm36', name: 'BISC ROSQUINHA FORTALEZA CHOCOLATE 300G', price: '1', image: '../../assets/produtos/roscas choc.png' },
  { id: 'm37', name: 'BISC ROSQUINHA FORTALEZA COCO 300G', price: '1', image: '../../assets/produtos/roscas coco.png' },
  { id: 'm38', name: 'CAFE MARATA VACUO 250G', price: '1', image: '../../assets/produtos/cafe marata.png' },
  { id: 'm39', name: 'CAFE SANTA CLARA CLASSIC VACUO 250G', price: '1', image: '../../assets/produtos/cafe santa clara.png' },
  { id: 'm40', name: 'CALDO MAGGI 57G CARNE', price: '1', image: '../../assets/produtos/maggi carne.png' },
  { id: 'm41', name: 'CALDO MAGGI 57G GALINHA', price: '1', image: '../../assets/produtos/maggi galinha.png' },
  { id: 'm42', name: 'CANETA BIC CRISTAL AZUL', price: '1', image: '../../assets/produtos/caneta.png' },
  { id: 'm43', name: 'COCO RALADO MENINA 50G', price: '1', image: '../../assets/produtos/coco ralado.png' },
  { id: 'm44', name: 'COLA MALUCA 2G', price: '1', image: '../../assets/produtos/cola.png' },
  { id: 'm45', name: 'COLORIFICO DONA CLARA 100G', price: '1', image: '../../assets/produtos/coloral.png' },
  { id: 'm46', name: 'CREME DENTAL COLGATE TRIPLA ACAO ORIGINAL 90G', price: '1', image: '../../assets/produtos/colgate.png' },
  { id: 'm47', name: 'CREME DENTAL SORRISO AZUL 50G', price: '1', image: '../../assets/produtos/sorriso.png' },
  { id: 'm48', name: 'CREME DE LEITE BETANIA 200G', price: '1', image: '../../assets/produtos/creme de leite.png' },
  { id: 'm49', name: 'CURATIVO COTTON', price: '1', image: '../../assets/produtos/curativo.png' },
  { id: 'm50', name: 'DESODORANTE DOVE AERO ORIGINAL 150ML', price: '1', image: '../../assets/produtos/dove aero.png' },
  { id: 'm51', name: 'DESODORANTE REXONA AERO FEM POWDER 150ML', price: '1', image: '../../assets/produtos/power dry.png' },
  { id: 'm52', name: 'DESODORANTE REXONA AERO MEN ACTIVE DRY 150ML', price: '1', image: '../../assets/produtos/active dry.png' },
  { id: 'm53', name: 'DESINFETANTE BAK YPE 500ML FLORAL', price: '1', image: '../../assets/produtos/ype floral.png' },
  { id: 'm54', name: 'DESINFETANTE BAK YPE 500ML LAVANDA', price: '1', image: '../../assets/produtos/ype lavanda.png' },
  { id: 'm55', name: 'DESINFETANTE MEU LAR 1L FLORAL (Azul escuro)', price: '1', image: '../../assets/produtos/meu lar.png' },
  { id: 'm56', name: 'DESINFETANTE MEU LAR 1L LAVANDA (Lilás)', price: '1', image: '../../assets/produtos/meu lar.png' },
  { id: 'm57', name: 'DESINFETANTE MEU LAR 1L NATURE (Verde)', price: '1', image: '../../assets/produtos/meu lar.png' },
  { id: 'm58', name: 'DESINFETANTE MEU LAR 1L  (Azul claro)', price: '1', image: '../../assets/produtos/meu lar.png' },
  { id: 'm59', name: 'DETERGENTE YPE LIMAO 500ML', price: '1', image: '../../assets/produtos/ype limao.png' },
  { id: 'm60', name: 'DETERGENTE YPE MACA 500ML', price: '1', image: '../../assets/produtos/ype maca.png' },
  { id: 'm61', name: 'DETERGENTE YPE NEUTRO 500ML', price: '1', image: '../../assets/produtos/ype neutro.png' },
  { id: 'm62', name: 'DUETO ODERICH LATA 200G', price: '1', image: '../../assets/produtos/dueto.png' },
  { id: 'm63', name: 'ERVILHA ODERICH LATA 200G', price: '1', image: '../../assets/produtos/ervilha.png' },
  { id: 'm64', name: 'ESCOVA DENTAL IMPORTADA ADULTO', price: '1', image: '../../assets/produtos/escova dental.png' },
  { id: 'm65', name: 'ESCOVA DENTAL IMPORTADA INFANTIL', price: '1', image: '../../assets/produtos/carrinho.png' },
  { id: 'm66', name: 'ESCOVA DENTAL ORAL-B PRO MEDIA', price: '1', image: '../../assets/produtos/carrinho.png' },
  { id: 'm67', name: 'ESCOVAO PLASTICO ANATOMICO', price: '1', image: '../../assets/produtos/carrinho.png' },
  { id: 'm68', name: 'ESPETINHO PARA CHURRASCO 30CM C/50', price: '1', image: '../../assets/produtos/carrinho.png' },
  { id: 'm69', name: 'ESPONJA DE ACO ASSOLAN C/8', price: '1', image: '../../assets/produtos/carrinho.png' },
  { id: 'm70', name: 'ESPONJA DUPLA FACE BRILHUS', price: '1', image: '../../assets/produtos/carrinho.png' },
  { id: 'm71', name: 'EXTRATO DE TOMATE FUGINI 300G', price: '1', image: '../../assets/produtos/carrinho.png' },
  { id: 'm72', name: 'FARINHA AMARELA PONTO DO FEIJAO 1KG', price: '1', image: '../../assets/produtos/carrinho.png' },
  { id: 'm73', name: 'FECULA JURITI 1KG', price: '1', image: '../../assets/produtos/carrinho.png' },
  { id: 'm74', name: 'FEIJAO CARIOCA PONTO DO FEIJAO 1KG', price: '1', image: '../../assets/produtos/carrinho.png' },
  { id: 'm75', name: 'FEIJAO CORDA PONTO DO FEIJAO 1KG', price: '1', image: '../../assets/produtos/carrinho.png' },
  { id: 'm76', name: 'FEIJAO PRETO PONTO DO FEIJAO 1KG', price: '1', image: '../../assets/produtos/carrinho.png' },
  { id: 'm77', name: 'FERMENTO QUIMICO DONA BENTA 100G', price: '1', image: '../../assets/produtos/carrinho.png' },
  { id: 'm78', name: 'FILME PVC BOMPACK 28CM X 15M', price: '1', image: '../../assets/produtos/carrinho.png' },
  { id: 'm79', name: 'FLOCAO DE MILHO DONA CLARA 500G', price: '1', image: '../../assets/produtos/carrinho.png' },
  { id: 'm80', name: 'FOSFOROS ARGOS MADEIRA', price: '1', image: '../../assets/produtos/carrinho.png' },
  { id: 'm81', name: 'GUARDANAPO SCALA', price: '1', image: '../../assets/produtos/carrinho.png' },
  { id: 'm82', name: 'HASTES FLEXIVEIS COTTON LINE', price: '1', image: '../../assets/produtos/carrinho.png' },
  { id: 'm83', name: 'INSETICIDA BAYGON AEROSOL ACAO TOTAL 360ML', price: '1', image: '../../assets/produtos/carrinho.png' },
  { id: 'm84', name: 'LAMEN NISSIN MIOJO CARNE 85G', price: '1', image: '../../assets/produtos/carrinho.png' },
  { id: 'm85', name: 'LAMEN NISSIN MIOJO GALINHA CAIPIRA 85G', price: '1', image: '../../assets/produtos/carrinho.png' },
  { id: 'm86', name: 'LAVA ROUPA LIQUIDO BRILHANTE 700ML', price: '1', image: '../../assets/produtos/carrinho.png' },
  { id: 'm87', name: 'LAVA ROUPA LIQUIDO OMO 700ML', price: '1', image: '../../assets/produtos/carrinho.png' },
  { id: 'm88', name: 'LAVA ROUPA LIQUIDO TIXAN YPE 700ML', price: '1', image: '../../assets/produtos/carrinho.png' },
  { id: 'm89', name: 'LEITE CONDENSADO BETANIA 395G', price: '1', image: '../../assets/produtos/carrinho.png' },
  { id: 'm90', name: 'LEITE DE COCO MENINA 200ML', price: '1', image: '../../assets/produtos/carrinho.png' },
  { id: 'm91', name: 'LEITE EM PO ITAMBE DESNATADO 200G', price: '1', image: '../../assets/produtos/carrinho.png' },
  { id: 'm92', name: 'LEITE EM PO ITAMBE INTEGRAL 200G', price: '1', image: '../../assets/produtos/carrinho.png' },
  { id: 'm93', name: 'LEITE UHT BETANIA DESNATADO 1L', price: '1', image: '../../assets/produtos/carrinho.png' },
  { id: 'm94', name: 'LEITE UHT BETANIA INTEGRAL 1L', price: '1', image: '../../assets/produtos/carrinho.png' },
  { id: 'm95', name: 'MACARRAO ESPAGUETE FORTALEZA SEMOLA 400G', price: '1', image: '../../assets/produtos/carrinho.png' },
  { id: 'm96', name: 'PAPEL HIGIENICO FLORAL 4X30M NEUTRO', price: '1', image: '../../assets/produtos/carrinho.png' },
  { id: 'm97', name: 'PAPEL HIGIENICO MIMMO FOLHA DUPLA 4X30M NEUTRO', price: '1', image: '../../assets/produtos/carrinho.png' },
  { id: 'm98', name: 'PAPEL TOALHA SCALA 2X60 TOALHAS', price: '1', image: '../../assets/produtos/carrinho.png' },
  { id: 'm99', name: 'POLIDOR LIMPA FACIL TRADICIONAL 500ML', price: '1', image: '../../assets/produtos/carrinho.png' },
  { id: 'm100', name: 'REFRESCO TANG 18G LIMAO', price: '1', image: '../../assets/produtos/carrinho.png' },
  { id: 'm101', name: 'REFRESCO TANG 18G MARACUJA', price: '1', image: '../../assets/produtos/carrinho.png' },
  { id: 'm102', name: 'REFRESCO TANG 18G MORANGO', price: '1', image: '../../assets/produtos/carrinho.png' },
  { id: 'm103', name: 'REFRESCO TANG 18G UVA', price: '1', image: '../../assets/produtos/carrinho.png' },
  { id: 'm104', name: 'REFRIGERANTE ANTARCTICA GUARANA 200ML', price: '2', image: '../../assets/produtos/carrinho.png' },
  { id: 'm105', name: 'REFRIGERANTE COCA-COLA 1L', price: '4', image: '../../assets/produtos/carrinho.png' },
  { id: 'm106', name: 'REFRIGERANTE COCA-COLA 1L ZERO', price: '4', image: '../../assets/produtos/carrinho.png' },
  { id: 'm107', name: 'REFRIGERANTE COCA-COLA 250ML PET', price: '3', image: '../../assets/produtos/carrinho.png' },
  { id: 'm108', name: 'REFRIGERANTE COCA-COLA 250ML ZERO PET', price: '3', image: '../../assets/produtos/carrinho.png' },
  { id: 'm109', name: 'REFRIGERANTE COCA-COLA 2L', price: '4', image: '../../assets/produtos/carrinho.png' },
  { id: 'm110', name: 'REFRIGERANTE COCA-COLA 2L ZERO', price: '4', image: '../../assets/produtos/carrinho.png' },
  { id: 'm111', name: 'REFRIGERANTE COCA-COLA LATA 350ML', price: '4', image: '../../assets/produtos/carrinho.png' },
  { id: 'm112', name: 'REFRIGERANTE COCA-COLA LATA 350ML ZERO', price: '4', image: '../../assets/produtos/carrinho.png' },
  { id: 'm113', name: 'REFRIGERANTE FANTA 250ML LARANJA PET', price: '2', image: '../../assets/produtos/carrinho.png' },
  { id: 'm114', name: 'REFRIGERANTE FANTA 250ML UVA PET', price: '2', image: '../../assets/produtos/carrinho.png' },
  { id: 'm115', name: 'REFRIGERANTE FANTA 2L LARANJA', price: '4', image: '../../assets/produtos/carrinho.png' },
  { id: 'm116', name: 'REFRIGERANTE FANTA 2L UVA', price: '4', image: '../../assets/produtos/carrinho.png' },
  { id: 'm117', name: 'REFRIGERANTE FANTA LATA 350ML LARANJA', price: '4', image: '../../assets/produtos/carrinho.png' },
  { id: 'm118', name: 'REFRIGERANTE FANTA LATA 350ML UVA', price: '4', image: '../../assets/produtos/carrinho.png' },
  { id: 'm119', name: 'REFRIGERANTE SAO GERALDO 1L CAJU', price: '4', image: '../../assets/produtos/carrinho.png' },
  { id: 'm120', name: 'REFRIGERANTE SAO GERALDO 2L CAJU', price: '4', image: '../../assets/produtos/carrinho.png' },
  { id: 'm121', name: 'REFRIGERANTE SAO GERALDO LATA 350ML CAJU', price: '2', image: '../../assets/produtos/carrinho.png' },
  { id: 'm122', name: 'REFRIGERANTE SAO GERALDO LATA 350ML CAJU ZERO', price: '2', image: '../../assets/produtos/carrinho.png' },
  { id: 'm123', name: 'REFRIGERANTE SPRITE LATA 350ML', price: '4', image: '../../assets/produtos/carrinho.png' },
  { id: 'm124', name: 'SABAO EM BARRA YPE NEUTRO 5X160G', price: '1', image: '../../assets/produtos/carrinho.png' },
  { id: 'm125', name: 'SABAO EM PO ALA 400G ROSAS E FLOR DE LIS', price: '1', image: '../../assets/produtos/carrinho.png' },
  { id: 'm126', name: 'SABAO EM PO BRILHANTE 400G AZUL', price: '1', image: '../../assets/produtos/carrinho.png' },
  { id: 'm127', name: 'SAL REFINADO ALTEZA 1KG', price: '1', image: '../../assets/produtos/carrinho.png' },
  { id: 'm128', name: 'SARDINHA GOMES DA COSTA EM OLEO 125G', price: '1', image: '../../assets/produtos/carrinho.png' },
  { id: 'm129', name: 'SHAMPOO SEDA 325ML ANTICASPA', price: '1', image: '../../assets/produtos/carrinho.png' },
  { id: 'm130', name: 'SHAMPOO SEDA 325ML CACHOS DEFINIDOS', price: '1', image: '../../assets/produtos/carrinho.png' },
  { id: 'm131', name: 'SHAMPOO SEDA 325ML LISO PERFEITO', price: '1', image: '../../assets/produtos/carrinho.png' },
  { id: 'm132', name: 'SUCO DEL VALLE KAPO UVA 200ML', price: '1', image: '../../assets/produtos/carrinho.png' },
  { id: 'm133', name: 'SUCO DEL VALLE KAPO UVA 200ML', price: '1', image: '../../assets/produtos/carrinho.png' },
  { id: 'm134', name: 'TRIGO FINNA COM FERMENTO 1KG', price: '1', image: '../../assets/produtos/carrinho.png' },
  { id: 'm135', name: 'TRIGO FINNA SEM FERMENTO 1KG', price: '1', image: '../../assets/produtos/carrinho.png' },
  { id: 'm136', name: 'VELA VIVACE N-10 PLUS 126G', price: '1', image: '../../assets/produtos/carrinho.png' },
  { id: 'm137', name: 'VINAGRE ALCOOL REGINA 500ML', price: '1', image: '../../assets/produtos/carrinho.png' },
],
  lanches: [
    { id: 'l1', name: 'Hambúrguer Artesanal', price: '15.90', desc: 'Hambúrguer 180g com queijo e bacon', image: '../../assets/produtos/carrinho.png' },
    { id: 'l2', name: 'Hot Dog Completo', price: '12.90', desc: 'Hot dog com batata palha e molhos', image: '../../assets/produtos/carrinho.png' },
    { id: 'l3', name: 'Sanduíche Natural', price: '8.90', desc: 'Sanduíche integral com peito de peru', image: '../../assets/produtos/carrinho.png' },
    { id: 'l4', name: 'Coxinha de Frango', price: '4.50', desc: 'Coxinha tradicional frita na hora', image: '../../assets/produtos/carrinho.png' },
    { id: 'l5', name: 'Pastel de Queijo', price: '5.90', desc: 'Pastel assado com queijo derretido', image: '../../assets/produtos/carrinho.png' },
    { id: 'l6', name: 'Pão de Açúcar', price: '3.50', desc: 'Pão doce tradicional', image: '../../assets/produtos/carrinho.png' },
    { id: 'l7', name: 'Empada de Palmito', price: '6.90', desc: 'Empada assada com palmito', image: '../../assets/produtos/carrinho.png' },
    { id: 'l8', name: 'Esfirra de Carne', price: '4.90', desc: 'Esfirra aberta com carne temperada', image: '../../assets/produtos/carrinho.png' },
    { id: 'l9', name: 'Pizza Fatia', price: '7.90', desc: 'Fatia de pizza margherita', image: '../../assets/produtos/carrinho.png' },
    { id: 'l10', name: 'Açaí 300ml', price: '9.90', desc: 'Açaí cremoso com granola', image: '../../assets/produtos/carrinho.png' },
    { id: 'l11', name: 'Vitamina de Banana', price: '6.50', desc: 'Vitamina natural com leite', image: '../../assets/produtos/carrinho.png' },
    { id: 'l12', name: 'Suco de Laranja', price: '5.90', desc: 'Suco natural 300ml', image: '../../assets/produtos/carrinho.png' },
    { id: 'l13', name: 'Café Expresso', price: '3.50', desc: 'Café expresso tradicional', image: '../../assets/produtos/carrinho.png' },
    { id: 'l14', name: 'Cappuccino', price: '5.90', desc: 'Cappuccino cremoso com canela', image: '../../assets/produtos/carrinho.png' },
    { id: 'l15', name: 'Chocolate Quente', price: '6.90', desc: 'Chocolate quente com marshmallow', image: '../../assets/produtos/carrinho.png' },
    { id: 'l16', name: 'Bolo de Cenoura', price: '4.90', desc: 'Fatia de bolo com cobertura', image: '../../assets/produtos/carrinho.png' },
    { id: 'l17', name: 'Pudim de Leite', price: '5.50', desc: 'Pudim caseiro individual', image: '../../assets/produtos/carrinho.png' },
    { id: 'l18', name: 'Brigadeiro Gourmet', price: '3.90', desc: 'Brigadeiro artesanal', image: '../../assets/produtos/carrinho.png' },
    { id: 'l19', name: 'Beijinho de Coco', price: '3.90', desc: 'Doce de coco tradicional', image: '../../assets/produtos/carrinho.png' },
    { id: 'l20', name: 'Torta de Limão', price: '6.90', desc: 'Fatia de torta com merengue', image: '../../assets/produtos/carrinho.png' },
    { id: 'l21', name: 'Croissant Presunto', price: '7.90', desc: 'Croissant com presunto e queijo', image: '../../assets/produtos/carrinho.png' },
    { id: 'l22', name: 'Misto Quente', price: '6.50', desc: 'Sanduíche quente tradicional', image: '../../assets/produtos/carrinho.png' },
    { id: 'l23', name: 'Bauru Completo', price: '11.90', desc: 'Bauru com rosbife e queijo', image: '../../assets/produtos/carrinho.png' },
    { id: 'l24', name: 'Wrap de Frango', price: '9.90', desc: 'Wrap integral com frango grelhado', image: '../../assets/produtos/carrinho.png' },
    { id: 'l25', name: 'Salada Caesar', price: '12.90', desc: 'Salada com frango e molho caesar', image: '../../assets/produtos/carrinho.png' },
    { id: 'l26', name: 'Quiche Lorraine', price: '8.90', desc: 'Quiche com bacon e queijo', image: '../../assets/produtos/carrinho.png' },
    { id: 'l27', name: 'Crepe Doce', price: '7.90', desc: 'Crepe com doce de leite', image: '../../assets/produtos/carrinho.png' },
    { id: 'l28', name: 'Crepe Salgado', price: '9.90', desc: 'Crepe com frango e catupiry', image: '../../assets/produtos/carrinho.png' },
    { id: 'l29', name: 'Milkshake Morango', price: '8.90', desc: 'Milkshake cremoso 400ml', image: '../../assets/produtos/carrinho.png' },
    { id: 'l30', name: 'Smoothie Verde', price: '9.90', desc: 'Smoothie detox com frutas', image: '../../assets/produtos/carrinho.png' }
  ], image: '../../assets/produtos/carrinho.png'
};
