const produtos = {
 petshop: [
  { id: 'p1', name: 'RACAO DOG CHOW ADULTO PEQUENOS KG', price: '16.00', image: '../../assets/produtos/dog chow.png' },
  { id: 'p2', name: 'RACAO MAGNUS CHIPS CARNE FRANGO KG', price: '10.50', image: '../../assets/produtos/magnus.png' },
  { id: 'p3', name: 'RACAO TRATTO PREMIUM ADULTO CARNE/CEREAIS KG', price: '9.5', image: '../../assets/produtos/tratto.png' },
  { id: 'p4', name: 'RACAO TRATTO PREMIUM FILHOTE CARNE KG', price: '10.5', image: '../../assets/produtos/tratto filhote.png' },
  { id: 'p5', name: 'RACAO CHANIN FILHOTE KG', price: '12.00', image: '../../assets/produtos/chanin filhote.png' },
  { id: 'p6', name: 'RACAO CHANIN CASTRADOS KG', price: '11.50', image: '../../assets/produtos/chanin castrado.png' },
  { id: 'p7', name: 'RACAO CHANIN CAT MIX KG', price: '11.00', image: '../../assets/produtos/chanin mix.png' },
  { id: 'p8', name: 'AREIA HIGIENICA GRIFFE CAT', price: '6.5', image: '../../assets/produtos/areia griffe.png' },
  { id: 'p9', name: 'AREIA HIGIENICA PERF ADG FLORAL', price: '9.9', image: '../../assets/produtos/areia perfumada.png' },
  { id: 'p10', name: 'WHISKAS SACHE ADULTO ATUM 85G', price: '3.9', image: '../../assets/produtos/sch atum.png' },
  { id: 'p11', name: 'PEDIGREE SACHE ADULTO RACA PEQUENA CARNE 100G', price: '3.9', image: '../../assets/produtos/sch carne ped.png' },
  { id: 'p12', name: 'PEDIGREE SACHE ADULTO RACA PEQUENA FRANGO 100G', price: '3.9', image: '../../assets/produtos/sch frango ped.png' },
  { id: 'p13', name: 'WHISKAS SACHE ADULTO FRANGO/MOLHO 85G', price: '3.9', image: '../../assets/produtos/sch frango.png' },
  { id: 'p14', name: 'RACAO WHISKAS PEIXE C/DELICROC KG', price: '21.00', image: '../../assets/produtos/whiskas peixe.png' },
],
mercearia: [
  { id: 'm19', name: 'APARELHO GILLETTE PRESTOBARBA', price: '6.50', image: '../../assets/produtos/gillete.png' },
  { id: 'm1', name: 'ACETONA ALYNE 100ML', price: '5.00', image: '../../assets/produtos/Acetona.png' },
  { id: 'm2', name: 'ABS INTIMUS GEL NOTURNO SUAVE C/ABAS C/8', price: '8.90', image: '../../assets/produtos/Intimus noturno.png' },
  { id: 'm3', name: 'ABS INTIMUS GEL TRIPLA SUAVE C/ABAS C/8', price: '4.70', image: '../../assets/produtos/Intimus suave c abas.png' },
  { id: 'm4', name: 'ABS INTIMUS GEL TRIPLA SUAVE S/ABAS C/8', price: '4.70', image: '../../assets/produtos/Intimus suave s abas.png' },
  { id: 'm160', name: 'ACHOCOLATADO NESCAU', price: '3.00', image: '../../assets/produtos/nescau.png' },
  { id: 'm161', name: 'ACUCAR CAETE', price: '4.50', image: '../../assets/produtos/acucar.png' },
  { id: 'm5', name: 'ADOCANTE ZERO-CAL 100ML', price: '10.50', image: '../../assets/produtos/adocante.png' },
  { id: 'm6', name: 'AGUA MINERAL INDAIA 500ML C/GAS', price: '3.00', image: '../../assets/produtos/Agua c gas.png' },
  { id: 'm7', name: 'AGUA MINERAL INDAIA 500ML S/GAS', price: '2.00', image: '../../assets/produtos/agua s gas.png' },
  { id: 'm8', name: 'AGUA SANITARIA BRILUX MULTI 1L', price: '4.00', image: '../../assets/produtos/brilux.png' },
  { id: 'm9', name: 'AGUA SANITARIA DRAGAO 1L', price: '3.00', image: '../../assets/produtos/dragao.png' },
  { id: 'm10', name: 'ALCOOL LIQUIDO SANTA CRUZ 70% 1L', price: '11.50', image: '../../assets/produtos/alcool.png' },
  { id: 'm11', name: 'ALGODAO NEVOA 25G', price: '2.00', image: '../../assets/produtos/algodao.png' },
  { id: 'm12', name: 'ALHO ROXO IMPORTADO KG', price: '20.00', image: '../../assets/produtos/alho.png' },
  { id: 'm13', name: 'AMACIANTE DOWNY 500ML BRISA INTENSA', price: '15.00', image: '../../assets/produtos/downy intenso.png' },
  { id: 'm14', name: 'AMACIANTE DOWNY 500ML BRISA VERAO', price: '15.00', image: '../../assets/produtos/downy brisa.png' },
  { id: 'm15', name: 'AMACIANTE DOWNY 500ML LIRIOS DO CAMPO', price: '15.00', image: '../../assets/produtos/downy lirios.png' },
  { id: 'm16', name: 'AMACIANTE SONHO 2L MAGIC', price: '12.50', image: '../../assets/produtos/sonho magic.png' },
  { id: 'm17', name: 'AMACIANTE SONHO 500ML MAGIC', price: '4.50', image: '../../assets/produtos/sonho magic 500.png' },
  { id: 'm18', name: 'AMACIANTE YPE 2L ACONCHEGO AZUL', price: '13.00', image: '../../assets/produtos/ype 2L.png' },
  { id: 'm20', name: 'ARROZ 101 BRANCO 1KG', price: '5.50', image: '../../assets/produtos/101 branco.png' },
  { id: 'm21', name: 'ARROZ 101 PARBOILIZADO 1KG', price: '5.50', image: '../../assets/produtos/101 parbolizado.png' },
  { id: 'm22', name: 'ARROZ ITAGUARY BRANCO 1KG', price: '4.70', image: '../../assets/produtos/carrinho.png' },
  { id: 'm23', name: 'ARROZ ITAGUARY PARBOILIZADO 1KG', price: '4.70', image: '../../assets/produtos/itaguary parbolizado.png' },
  { id: 'm24', name: 'AVEIA QUAKER FLOCOS FINOS 165G', price: '5.60', image: '../../assets/produtos/aveia flocos finos.png' },
  { id: 'm25', name: 'AVEIA QUAKER FLOCOS REGULAR 165G', price: '5.60', image: '../../assets/produtos/aveia flocos regular.png' },
  { id: 'm27', name: 'BISC CREAM CRACKER FORTALEZA 350G', price: '6.50', image: '../../assets/produtos/cream cracker.png' },
  { id: 'm28', name: 'BISC FORTALEZA MAIZENA 350G', price: '8.00', image: '../../assets/produtos/bisc maizena.png' },
  { id: 'm29', name: 'BISC FORTALEZA POP SALGADA 400G', price: '6.60', image: '../../assets/produtos/cracker mini.png' },
  { id: 'm30', name: 'BISC PIRAQUE MALTADO COBERTO 80G', price: '5.50', image: '../../assets/produtos/piraque maltado.png' },
  { id: 'm31', name: 'BISC RECHEADO ANIMADOS QUADRADO 130G CHOCOLATE', price: '4.00', image: '../../assets/produtos/animados choc.png' },
  { id: 'm32', name: 'BISC RECHEADO ANIMADOS QUADRADO 130G MORANGO', price: '4.00', image: '../../assets/produtos/animados moran.png' },
  { id: 'm33', name: 'BISC RECHEADO RICHESTER AMORI 125G CHOCOLATE', price: '3.00', image: '../../assets/produtos/amori choc.png' },
  { id: 'm34', name: 'BISC RECHEADO RICHESTER AMORI 125G ESCURO', price: '3.00', image: '../../assets/produtos/escureto.png' },
  { id: 'm35', name: 'BISC RECHEADO RICHESTER AMORI 125G MORANGO', price: '3.00', image: '../../assets/produtos/amori morango.png' },
  { id: 'm36', name: 'BISC ROSQUINHA FORTALEZA CHOCOLATE 300G', price: '6.50', image: '../../assets/produtos/roscas choc.png' },
  { id: 'm37', name: 'BISC ROSQUINHA FORTALEZA COCO 300G', price: '6.50', image: '../../assets/produtos/roscas coco.png' },
  { id: 'm38', name: 'CAFE MARATA VACUO 250G', price: '16.00', image: '../../assets/produtos/cafe marata.png' },
  { id: 'm39', name: 'CAFE SANTA CLARA CLASSIC VACUO 250G', price: '18.50', image: '../../assets/produtos/cafe santa clara.png' },
  { id: 'm40', name: 'CALDO MAGGI 57G CARNE', price: '2.80', image: '../../assets/produtos/maggi carne.png' },
  { id: 'm41', name: 'CALDO MAGGI 57G GALINHA', price: '2.80', image: '../../assets/produtos/maggi galinha.png' },
  { id: 'm42', name: 'CANETA BIC CRISTAL AZUL', price: '1.50', image: '../../assets/produtos/caneta.png' },
  { id: 'm166', name: 'CERVEJA BRAHMA DUPLO MALTE 350ML', price: '5.00', image: '../../assets/produtos/brahma.png' },
  { id: 'm167', name: 'CERVEJA BUDWEISER LONG NECK 330ML', price: '7.00', image: '../../assets/produtos/bud.png' },
  { id: 'm168', name: 'CERVEJA SPATEN 350ML', price: '6.50', image: '../../assets/produtos/spaten.png' },
  { id: 'm43', name: 'COCO RALADO MENINA 50G', price: '2.75', image: '../../assets/produtos/coco ralado.png' },
  { id: 'm44', name: 'COLA MALUCA 2G', price: '2.00', image: '../../assets/produtos/cola.png' },
  { id: 'm45', name: 'COLORIFICO DONA CLARA 100G', price: '1.50', image: '../../assets/produtos/coloral.png' },
  { id: 'm46', name: 'CREME DENTAL COLGATE TRIPLA ACAO ORIGINAL 90G', price: '5.50', image: '../../assets/produtos/colgate.png' },
  { id: 'm47', name: 'CREME DENTAL SORRISO AZUL 50G', price: '3.85', image: '../../assets/produtos/sorriso.png' },
  { id: 'm48', name: 'CREME DE LEITE BETANIA 200G', price: '3.85', image: '../../assets/produtos/creme de leite.png' },
  { id: 'm49', name: 'CURATIVO COTTON UND', price: '0.50', image: '../../assets/produtos/curativo.png' },
  { id: 'm50', name: 'DESODORANTE DOVE AERO ORIGINAL 150ML', price: '16.50', image: '../../assets/produtos/dove aero.png' },
  { id: 'm51', name: 'DESODORANTE REXONA AERO FEM POWDER 150ML', price: '15.50', image: '../../assets/produtos/power dry.png' },
  { id: 'm52', name: 'DESODORANTE REXONA AERO MEN ACTIVE DRY 150ML', price: '15.50', image: '../../assets/produtos/active dry.png' },
  { id: 'm53', name: 'DESINFETANTE BAK YPE 500ML FLORAL', price: '4.70', image: '../../assets/produtos/ype floral.png' },
  { id: 'm54', name: 'DESINFETANTE BAK YPE 500ML LAVANDA', price: '4.70', image: '../../assets/produtos/ype lavanda.png' },
  { id: 'm55', name: 'DESINFETANTE MEU LAR 1L FLORAL', price: '5.00', image: '../../assets/produtos/meu lar.png' },
  { id: 'm56', name: 'DESINFETANTE MEU LAR 1L LAVANDA', price: '5.00', image: '../../assets/produtos/meu lar.png' },
  { id: 'm57', name: 'DESINFETANTE MEU LAR 1L NATURE', price: '5.00', image: '../../assets/produtos/meu lar.png' },
  { id: 'm58', name: 'DESINFETANTE MEU LAR 1L OCEANIC', price: '5.00', image: '../../assets/produtos/meu lar.png' },
  { id: 'm163', name: 'DETERGENTE YPE COCO 500ML', price: '3.00', image: '../../assets/produtos/ype coco.png' },
  { id: 'm59', name: 'DETERGENTE YPE LIMAO 500ML', price: '3.00', image: '../../assets/produtos/ype limao.png' },
  { id: 'm60', name: 'DETERGENTE YPE MACA 500ML', price: '3.00', image: '../../assets/produtos/ype maca.png' },
  { id: 'm61', name: 'DETERGENTE YPE NEUTRO 500ML', price: '3.00', image: '../../assets/produtos/ype neutro.png' },
  { id: 'm62', name: 'DUETO ODERICH LATA 200G', price: '4.00', image: '../../assets/produtos/dueto.png' },
  { id: 'm63', name: 'ERVILHA ODERICH LATA 200G', price: '3.90', image: '../../assets/produtos/ervilha.png' },
  { id: 'm64', name: 'ESCOVA DENTAL IMPORTADA ADULTO', price: '3.00', image: '../../assets/produtos/escova dental.png' },
  { id: 'm65', name: 'ESCOVA DENTAL IMPORTADA INFANTIL', price: '3.00', image: '../../assets/produtos/escova infantil.png' },
  { id: 'm66', name: 'ESCOVA DENTAL ORAL-B PRO MEDIA', price: '4.50', image: '../../assets/produtos/escova oral b.png' },
  { id: 'm67', name: 'ESCOVAO PLASTICO ANATOMICO', price: '4.00', image: '../../assets/produtos/escovao.png' },
  { id: 'm68', name: 'ESPETINHO PARA CHURRASCO 30CM C/50', price: '4.50', image: '../../assets/produtos/espeto p churrasco.png' },
  { id: 'm69', name: 'ESPONJA DE ACO ASSOLAN C/8', price: '2.50', image: '../../assets/produtos/assolan.png' },
  { id: 'm70', name: 'ESPONJA DUPLA FACE BRILHUS', price: '1.50', image: '../../assets/produtos/esponja brilhus.png' },
  { id: 'm71', name: 'EXTRATO DE TOMATE FUGINI 300G', price: '4.00', image: '../../assets/produtos/extrato de tomate.png' },
  { id: 'm72', name: 'FARINHA AMARELA PONTO DO FEIJAO 1KG', price: '6.00', image: '../../assets/produtos/carrinho.png' },
  { id: 'm73', name: 'FECULA JURITI 1KG', price: '7.50', image: '../../assets/produtos/juriti.png' },
  { id: 'm74', name: 'FEIJAO CARIOCA PONTO DO FEIJAO 1KG', price: '8.50', image: '../../assets/produtos/carrinho.png' },
  { id: 'm75', name: 'FEIJAO CORDA PONTO DO FEIJAO 1KG', price: '6.00', image: '../../assets/produtos/carrinho.png' },
  { id: 'm76', name: 'FEIJAO PRETO PONTO DO FEIJAO 1KG', price: '7.50', image: '../../assets/produtos/carrinho.png' },
  { id: 'm77', name: 'FERMENTO QUIMICO DONA BENTA 100G', price: '5.50', image: '../../assets/produtos/fermento em po.png' },
  { id: 'm78', name: 'FILME PVC BO 28CM X 15M', price: '5.50', image: '../../assets/produtos/filme pvc.png' },
  { id: 'm79', name: 'FLOCAO DE MILHO DONA CLARA 500G', price: '2.50', image: '../../assets/produtos/flocao.png' },
  { id: 'm80', name: 'FOSFOROS ARGOS MADEIRA CX', price: '1.2', image: '../../assets/produtos/fosforo.png' },
  { id: 'm81', name: 'GUARDANAPO SCALA', price: '2.50', image: '../../assets/produtos/guardanapos.png' },
  { id: 'm82', name: 'HASTES FLEXIVEIS COTTON LINE', price: '2.50', image: '../../assets/produtos/cotonete.png' },
  { id: 'm83', name: 'INSETICIDA BAYGON AEROSOL ACAO TOTAL 360ML', price: '14.50', image: '../../assets/produtos/baygon.png' },
  { id: 'm164', name: 'ISQUEIRO BIC MAXI', price: '5.50', image: '../../assets/produtos/isqueiro.png' },
  { id: 'm84', name: 'LAMEN NISSIN MIOJO CARNE 85G', price: '3.00', image: '../../assets/produtos/nissin carne.png' },
  { id: 'm85', name: 'LAMEN NISSIN MIOJO GALINHA CAIPIRA 85G', price: '3.00', image: '../../assets/produtos/nissin galinha.png' },
  { id: 'm86', name: 'LAVA ROUPA LIQUIDO BRILHANTE 700ML', price: '10.50', image: '../../assets/produtos/brilhante.png' },
  { id: 'm87', name: 'LAVA ROUPA LIQUIDO OMO 700ML', price: '14.50', image: '../../assets/produtos/omo.png' },
  { id: 'm88', name: 'LAVA ROUPA LIQUIDO TIXAN YPE 700ML', price: '13.00', image: '../../assets/produtos/carrinho.png' },
  { id: 'm89', name: 'LEITE CONDENSADO BETANIA 395G', price: '8.50', image: '../../assets/produtos/leite condensado.png' },
  { id: 'm90', name: 'LEITE DE COCO MENINA 200ML', price: '5.50', image: '../../assets/produtos/leite de coco.png' },
  { id: 'm91', name: 'LEITE EM PO ITAMBE DESNATADO 200G', price: '9.50', image: '../../assets/produtos/leite des 200.png' },
  { id: 'm92', name: 'LEITE EM PO ITAMBE INTEGRAL 200G', price: '8.50', image: '../../assets/produtos/leite int 200.png' },
  { id: 'm93', name: 'LEITE UHT BETANIA DESNATADO 1L', price: '8.00', image: '../../assets/produtos/leite des 1L.png' },
  { id: 'm94', name: 'LEITE UHT BETANIA INTEGRAL 1L', price: '7.80', image: '../../assets/produtos/leite int 1L.png' },
  { id: 'm95', name: 'MACARRAO ESPAGUETE BONSABOR COMUM 400G', price: '4.00', image: '../../assets/produtos/espaguete bom sabor.png' },
  { id: 'm96', name: 'MACARRAO ESPAGUETE FORTALEZA SEMOLA 400G', price: '5.00', image: '../../assets/produtos/espaguete fortaleza.png' },
  { id: 'm97', name: 'MACARRAO ESPAGUETE GOSTOSO COMUM 400G', price: '4.50', image: '../../assets/produtos/espaguete gostoso.png' },
  { id: 'm98', name: 'MACARRAO LASANHA ESTRELA SEMOLA 500G', price: '11.50', image: '../../assets/produtos/lasanha estrela.png' },
  { id: 'm99', name: 'MAIONESE HELLMANNS SACHE 200G', price: '6.90', image: '../../assets/produtos/maionese.png' },
  { id: 'm162', name: 'MAIZENA 200G', price: '5.50', image: '../../assets/produtos/maizena.png' },
  { id: 'm100', name: 'MARGARINA PURO SABOR C/SAL 250G', price: '3.70', image: '../../assets/produtos/puro sabor 250.png' },
  { id: 'm101', name: 'MARGARINA PURO SABOR C/SAL 500G', price: '7.50', image: '../../assets/produtos/puro sabor 500.png' },
  { id: 'm102', name: 'MARGARINA QUALY CREMOSA C/SAL 250G', price: '6.90', image: '../../assets/produtos/qualy 250.png' },
  { id: 'm103', name: 'MARGARINA QUALY CREMOSA C/SAL 500G', price: '12.50', image: '../../assets/produtos/qualy 500.png' },
  { id: 'm104', name: 'MASSA P/TAPIOCA PRECIOSO 1KG', price: '8.00', image: '../../assets/produtos/tapioca.png' },
  { id: 'm105', name: 'MILHO VERDE FUGINI SACHE 170G', price: '4.00', image: '../../assets/produtos/milho verde.png' },
  { id: 'm106', name: 'MOLHO DE TOMATE FUGINI TRADICIONAL SACHE 300G', price: '2.50', image: '../../assets/produtos/molho de tomate.png' },
  { id: 'm107', name: 'MUCILON 180G ARROZ E AVEIA SACHE', price: '7.20', image: '../../assets/produtos/mucilon arroz.png' },
  { id: 'm108', name: 'MUCILON 180G MULTICEREAIS SACHE', price: '7.20', image: '../../assets/produtos/mucilon multicereais.png' },
  { id: 'm109', name: 'MULTIUSO VEJA 500ML ORIGINAL AZUL', price: '6.40', image: '../../assets/produtos/veja azul.png' },
  { id: 'm110', name: 'OLEO DE SOJA SOYA PET 900ML', price: '11.00', image: '../../assets/produtos/oleo.png' },
  { id: 'm111', name: 'PALITO DENTAL GINA C/100', price: '1.50', image: '../../assets/produtos/palito.png' },
  { id: 'm112', name: 'PAPEL HIGIENICO FLORAL 4X30M NEUTRO', price: '4.80', image: '../../assets/produtos/floral neutro.png' },
  { id: 'm113', name: 'PAPEL HIGIENICO MIMMO FOLHA DUPLA 4X30M NEUTRO', price: '8.50', image: '../../assets/produtos/mimmo.png' },
  { id: 'm114', name: 'PAPEL TOALHA SCALA 2X60 TOALHAS', price: '6.75', image: '../../assets/produtos/papel toalha.png' },
  { id: 'm115', name: 'POLIDOR LIMPA FACIL TRADICIONAL 500ML', price: '2.50', image: '../../assets/produtos/limpa facil.png' },
  { id: 'm116', name: 'REFRESCO TANG 18G LIMAO', price: '1.50', image: '../../assets/produtos/tang limao.png' },
  { id: 'm117', name: 'REFRESCO TANG 18G MARACUJA', price: '1.50', image: '../../assets/produtos/tang maracuja.png' },
  { id: 'm118', name: 'REFRESCO TANG 18G MORANGO', price: '1.50', image: '../../assets/produtos/tang morango.png' },
  { id: 'm119', name: 'REFRESCO TANG 18G UVA', price: '1.50', image: '../../assets/produtos/tang uva.png' },
  { id: 'm120', name: 'REFRIGERANTE ANTARCTICA 200ML GUARANA', price: '2.50', image: '../../assets/produtos/guarana 200.png' },
  { id: 'm121', name: 'REFRIGERANTE COCA-COLA 1L', price: '10.00', image: '../../assets/produtos/coca 1L.png' },
  { id: 'm122', name: 'REFRIGERANTE COCA-COLA 1L ZERO', price: '10.00', image: '../../assets/produtos/coca zero 1L.png' },
  { id: 'm125', name: 'REFRIGERANTE COCA-COLA 2L', price: '14.00', image: '../../assets/produtos/coca 2L.png' },
  { id: 'm126', name: 'REFRIGERANTE COCA-COLA 2L ZERO', price: '14.00', image: '../../assets/produtos/coca zero 2L.png' },
  { id: 'm123', name: 'REFRIGERANTE COCA-COLA 250ML PET', price: '3.50', image: '../../assets/produtos/coca 250.png' },
  { id: 'm124', name: 'REFRIGERANTE COCA-COLA 250ML ZERO PET', price: '3.50', image: '../../assets/produtos/coca zero 250.png' },
  { id: 'm128', name: 'REFRIGERANTE COCA-COLA 350ML LT S/ACUCAR', price: '4.50', image: '../../assets/produtos/coca zero 350.png' },
  { id: 'm127', name: 'REFRIGERANTE COCA-COLA LATA 350ML LT', price: '4.50', image: '../../assets/produtos/coca 350.png' },
  { id: 'm131', name: 'REFRIGERANTE FANTA 2L LARANJA', price: '12.00', image: '../../assets/produtos/laranja 2L.png' },
  { id: 'm132', name: 'REFRIGERANTE FANTA 2L UVA', price: '12.00', image: '../../assets/produtos/uva 2L.png' },
  { id: 'm129', name: 'REFRIGERANTE FANTA 250ML LARANJA PET', price: '3.00', image: '../../assets/produtos/laranja 250.png' },
  { id: 'm130', name: 'REFRIGERANTE FANTA 250ML UVA PET', price: '3.00', image: '../../assets/produtos/uva 250.png' },
  { id: 'm133', name: 'REFRIGERANTE FANTA 350ML LARANJA LT', price: '4.00', image: '../../assets/produtos/laranja 350.png' },
  { id: 'm134', name: 'REFRIGERANTE FANTA 350ML UVA LT', price: '4.00', image: '../../assets/produtos/uva 350.png' },
  { id: 'm135', name: 'REFRIGERANTE SAO GERALDO 1L CAJU', price: '10.00', image: '../../assets/produtos/cajuina 1L.png' },
  { id: 'm136', name: 'REFRIGERANTE SAO GERALDO 2L CAJU', price: '14.00', image: '../../assets/produtos/cajuina 2L.png' },
  { id: 'm137', name: 'REFRIGERANTE SAO GERALDO 350ML CAJU LT', price: '4.50', image: '../../assets/produtos/cajuina 350.png' },
  { id: 'm138', name: 'REFRIGERANTE SAO GERALDO 350ML CAJU ZERO LT', price: '4.50', image: '../../assets/produtos/cajuina zero 350.png' },
  { id: 'm139', name: 'REFRIGERANTE SPRITE 350ML LT', price: '4.00', image: '../../assets/produtos/sprite 350.png' },
  { id: 'm145', name: 'SABAO EM BARRA YPE NEUTRO 160G UND', price: '3.20', image: '../../assets/produtos/sabao em barra.png' },
  { id: 'm146', name: 'SABAO EM PO ALA 400G ROSAS E FLOR DE LIS', price: '4.50', image: '../../assets/produtos/ala.png' },
  { id: 'm147', name: 'SABAO EM PO BRILHANTE 400G AZUL LIMPT', price: '7.00', image: '../../assets/produtos/brilhante 400g.png' },
  { id: 'm140', name: 'SABONETE EVEN BARRA 85G ALOE VERA', price: '2.50', image: '../../assets/produtos/even aloe.png' },
  { id: 'm165', name: 'SABONETE EVEN BUQUE DE ROSAS 85G', price: '2.50', image: '../../assets/produtos/even buque.png' },
  { id: 'm141', name: 'SABONETE EVEN CAMPOS DE LAVANDA 85G', price: '2.50', image: '../../assets/produtos/even lavanda.png' },
  { id: 'm142', name: 'SABONETE EVEN EXT ALGAS MARINHAS 85G', price: '2.50', image: '../../assets/produtos/even algas.png' },
  { id: 'm143', name: 'SABONETE EVEN MEN 85G', price: '3.90', image: '../../assets/produtos/even men.png' },
  { id: 'm144', name: 'SABONETE PROTEX LIMPEZA PROFUNDA 85G', price: '3.90', image: '../../assets/produtos/protex.png' },
  { id: 'm148', name: 'SAL REFINADO ALTEZA 1KG', price: '2.00', image: '../../assets/produtos/sal.png' },
  { id: 'm149', name: 'SARDINHA GOMES DA COSTA EM OLEO 125G', price: '7.00', image: '../../assets/produtos/sardinha.png' },
  { id: 'm150', name: 'SHAMPOO SEDA 325ML ANTICASPA', price: '16.90', image: '../../assets/produtos/seda anticaspa.png' },
  { id: 'm151', name: 'SHAMPOO SEDA 325ML CACHOS DEFINIDOS', price: '16.90', image: '../../assets/produtos/seda cachos.png' },
  { id: 'm152', name: 'SHAMPOO SEDA 325ML CERAMIDAS', price: '16.90', image: '../../assets/produtos/seda ceramidas.png' },
  { id: 'm153', name: 'SHAMPOO SEDA 325ML LISO PERFEITO', price: '16.90', image: '../../assets/produtos/seda liso.png' },
  { id: 'm154', name: 'SUCO DEL VALLE KAPO MORANGO 200ML', price: '3.20', image: '../../assets/produtos/kapo morango.png' },
  { id: 'm155', name: 'SUCO DEL VALLE KAPO UVA 200ML', price: '3.20', image: '../../assets/produtos/kapo uva.png' },
  { id: 'm26', name: 'TAMPICO 330ML', price: '3.50', image: '../../assets/produtos/tampico 330ml.png' },
  { id: 'm156', name: 'TRIGO FINNA PAPEL COM FERMENTO 1KG', price: '6.00', image: '../../assets/produtos/finna c fermento.png' },
  { id: 'm157', name: 'TRIGO FINNA PAPEL SEM FERMENTO 1KG', price: '5.50', image: '../../assets/produtos/finna s fermento.png' },
  { id: 'm158', name: 'VELA VIVACE N-10 PLUS 126G', price: '5.00', image: '../../assets/produtos/vela.png' },
  { id: 'm159', name: 'VINAGRE ALCOOL REGINA 500ML', price: '2.50', image: '../../assets/produtos/vinagre.png' },
  { id: 'm160', name: 'COPOS 180ML', price: '6.00', image: '../../assets/produtos/copos.png' },
  { id: 'm161', name: 'PRATOS RASOS', price: '2.00', image: '../../assets/produtos/prato raso.png' },
  { id: 'm162', name: 'PRATOS FUNDOS', price: '2.00', image: '../../assets/produtos/prato fundo.png' },
  { id: 'm163', name: 'MENTOS', price: '3.00', image: '../../assets/produtos/mentos.png' },
  { id: 'm164', name: 'NUCITA', price: '0.50', image: '../../assets/produtos/nucita.png' },
  { id: 'm165', name: 'HALLS', price: '2.00', image: '../../assets/produtos/halls.png' },
  { id: 'm166', name: 'TRIDENT', price: '2.50', image: '../../assets/produtos/trident.png' },
  { id: 'm167', name: 'XILITOS LIPY', price: '2.50', image: '../../assets/produtos/xilito.png' },
  { id: 'm167', name: 'BATON GAROTO', price: '2.00', image: '../../assets/produtos/baton.png' },
],
  lanches: [
    { id: 'l1', name: 'Hambúrguer Artesanal', price: '15.90', desc: 'Hambúrguer 180g com queijo e bacon', image: '../../assets/produtos/carrinho.png' },
    { id: 'l2', name: 'Hot Dog Completo', price: '12.90', desc: 'Hot dog com batata palha e molhos', image: '../../assets/produtos/carrinho.png' },
    { id: 'l3', name: 'Sanduíche Natural', price: '8.90', desc: 'Sanduíche integral com peito de peru', image: '../../assets/produtos/carrinho.png' },
    { id: 'l4', name: 'Coxinha de Frango', price: '4.50', desc: 'Coxinha tradicional frita na hora', image: '../../assets/produtos/carrinho.png' },
    { id: 'l5', name: 'Pastel de Queijo', price: '5.90', desc: 'Pastel assado com queijo derretido', image: '../../assets/produtos/carrinho.png' },
    { id: 'l6', name: 'Pão de Açúcar', price: '3.50', desc: 'Pão doce tradicional', image: '../../assets/produtos/carrinho.png' },
    { id: 'l7', name: 'Empada de Palmito', price: '6.90', desc: 'Empada assada com palmito', image: '../../assets/produtos/carrinho.png' },
    { id: 'l8', name: 'Esfirra de Carne', price: '4.90', desc: 'Esfirra aberta com carne temperada', image: '../../assets/produtos/carrinho.png' },
    { id: 'l9', name: 'Pizza Fatia', price: '7.90', desc: 'Fatia de pizza margherita', image: '../../assets/produtos/carrinho.png' },
    { id: 'l10', name: 'Açaí 300ml', price: '9.90', desc: 'Açaí cremoso com granola', image: '../../assets/produtos/carrinho.png' },
    { id: 'l11', name: 'Vitamina de Banana', price: '6.50', desc: 'Vitamina natural com leite', image: '../../assets/produtos/carrinho.png' },
    { id: 'l12', name: 'Suco de Laranja', price: '5.90', desc: 'Suco natural 300ml', image: '../../assets/produtos/carrinho.png' },
    { id: 'l13', name: 'Café Expresso', price: '3.50', desc: 'Café expresso tradicional', image: '../../assets/produtos/carrinho.png' },
    { id: 'l14', name: 'Cappuccino', price: '5.90', desc: 'Cappuccino cremoso com canela', image: '../../assets/produtos/carrinho.png' },
    { id: 'l15', name: 'Chocolate Quente', price: '6.90', desc: 'Chocolate quente com marshmallow', image: '../../assets/produtos/carrinho.png' },
    { id: 'l16', name: 'Bolo de Cenoura', price: '4.90', desc: 'Fatia de bolo com cobertura', image: '../../assets/produtos/carrinho.png' },
    { id: 'l17', name: 'Pudim de Leite', price: '5.50', desc: 'Pudim caseiro individual', image: '../../assets/produtos/carrinho.png' },
    { id: 'l18', name: 'Brigadeiro Gourmet', price: '3.90', desc: 'Brigadeiro artesanal', image: '../../assets/produtos/carrinho.png' },
    { id: 'l19', name: 'Beijinho de Coco', price: '3.90', desc: 'Doce de coco tradicional', image: '../../assets/produtos/carrinho.png' },
    { id: 'l20', name: 'Torta de Limão', price: '6.90', desc: 'Fatia de torta com merengue', image: '../../assets/produtos/carrinho.png' },
    { id: 'l21', name: 'Croissant Presunto', price: '7.90', desc: 'Croissant com presunto e queijo', image: '../../assets/produtos/carrinho.png' },
    { id: 'l22', name: 'Misto Quente', price: '6.50', desc: 'Sanduíche quente tradicional', image: '../../assets/produtos/carrinho.png' },
    { id: 'l23', name: 'Bauru Completo', price: '11.90', desc: 'Bauru com rosbife e queijo', image: '../../assets/produtos/carrinho.png' },
    { id: 'l24', name: 'Wrap de Frango', price: '9.90', desc: 'Wrap integral com frango grelhado', image: '../../assets/produtos/carrinho.png' },
    { id: 'l25', name: 'Salada Caesar', price: '12.90', desc: 'Salada com frango e molho caesar', image: '../../assets/produtos/carrinho.png' },
    { id: 'l26', name: 'Quiche Lorraine', price: '8.90', desc: 'Quiche com bacon e queijo', image: '../../assets/produtos/carrinho.png' },
    { id: 'l27', name: 'Crepe Doce', price: '7.90', desc: 'Crepe com doce de leite', image: '../../assets/produtos/carrinho.png' },
    { id: 'l28', name: 'Crepe Salgado', price: '9.90', desc: 'Crepe com frango e catupiry', image: '../../assets/produtos/carrinho.png' },
    { id: 'l29', name: 'Milkshake Morango', price: '8.90', desc: 'Milkshake cremoso 400ml', image: '../../assets/produtos/carrinho.png' },
    { id: 'l30', name: 'Smoothie Verde', price: '9.90', desc: 'Smoothie detox com frutas', image: '../../assets/produtos/carrinho.png' }
  ], image: '../../assets/produtos/carrinho.png'
};
