const produtos = {
  petshop: [
    { id: 'p1', name: 'Ração Golden Cães', price: '89.90', desc: 'Ração premium para cães adultos 15kg', image: '../../assets/img/carrinho.png' },
    { id: 'p2', name: 'Ração Whiskas Gatos', price: '45.90', desc: 'Ração para gatos adultos sabor peixe 3kg', image: '../../assets/img/carrinho.png' },
    { id: 'p3', name: 'Coleira Antipulgas', price: '29.90', desc: 'Proteção por 8 meses contra pulgas', image: '../../assets/img/carrinho.png' },
    { id: 'p4', name: 'Brinquedo Mordedor', price: '19.90', desc: 'Osso de borracha resistente', image: '../../assets/img/carrinho.png' },
    { id: 'p5', name: 'Shampoo Pet Clean', price: '24.90', desc: 'Shampoo neutro para cães e gatos 500ml', image: '../../assets/img/carrinho.png' },
    { id: 'p6', name: 'Areia Sanitária', price: '15.90', desc: 'Areia higiênica para gatos 4kg', image: '../../assets/img/carrinho.png' },
    { id: 'p7', name: 'Comedouro Inox', price: '35.90', desc: 'Comedouro duplo em aço inoxidável', image: '../../assets/img/carrinho.png' },
    { id: 'p8', name: 'Guia Retrátil', price: '42.90', desc: 'Guia automática 5 metros para cães', image: '../../assets/img/carrinho.png' },
    { id: 'p9', name: 'Petisco Natural', price: '18.90', desc: 'Bifinho de frango desidratado 500g', image: '../../assets/img/carrinho.png' },
    { id: 'p10', name: 'Cama Pet Confort', price: '79.90', desc: 'Cama ortopédica tamanho médio', image: '../../assets/img/carrinho.png' },
    { id: 'p11', name: 'Vermífugo Total', price: '32.90', desc: 'Vermífugo para cães e gatos 4 comprimidos', image: '../../assets/img/carrinho.png' },
    { id: 'p12', name: 'Escova Dental Pet', price: '12.90', desc: 'Kit escova + pasta dental para pets', image: '../../assets/img/carrinho.png' },
    { id: 'p13', name: 'Casinha Plástica', price: '159.90', desc: 'Casa para cães médios resistente', image: '../../assets/img/carrinho.png' },
    { id: 'p14', name: 'Antipulgas Spray', price: '28.90', desc: 'Spray repelente natural 200ml', image: '../../assets/img/carrinho.png' },
    { id: 'p15', name: 'Ração Pássaros', price: '22.90', desc: 'Mistura de sementes premium 1kg', image: '../../assets/img/carrinho.png' },
    { id: 'p16', name: 'Bola Interativa', price: '26.90', desc: 'Bola com som e luzes para cães', image: '../../assets/img/carrinho.png' },
    { id: 'p17', name: 'Cortador de Unhas', price: '15.90', desc: 'Alicate para unhas de cães e gatos', image: '../../assets/img/carrinho.png' },
    { id: 'p18', name: 'Tapete Higiênico', price: '39.90', desc: 'Pacote com 30 tapetes absorventes', image: '../../assets/img/carrinho.png' },
    { id: 'p19', name: 'Ração Hamster', price: '18.90', desc: 'Alimento completo para roedores 500g', image: '../../assets/img/carrinho.png' },
    { id: 'p20', name: 'Aquário Completo', price: '189.90', desc: 'Kit aquário 20L com filtro e bomba', image: '../../assets/img/carrinho.png' },
    { id: 'p21', name: 'Ração Peixe', price: '14.90', desc: 'Alimento em flocos para peixes 100g', image: '../../assets/img/carrinho.png' },
    { id: 'p22', name: 'Transportadora', price: '89.90', desc: 'Caixa de transporte para gatos', image: '../../assets/img/carrinho.png' },
    { id: 'p23', name: 'Escova Pelos', price: '21.90', desc: 'Escova removedora de pelos mortos', image: '../../assets/img/carrinho.png' },
    { id: 'p24', name: 'Vitamina Pet', price: '45.90', desc: 'Suplemento vitamínico 60 cápsulas', image: '../../assets/img/carrinho.png' },
    { id: 'p25', name: 'Brinquedo Corda', price: '16.90', desc: 'Corda de algodão para cães', image: '../../assets/img/carrinho.png' },
    { id: 'p26', name: 'Colchonete Térmico', price: '65.90', desc: 'Manta térmica para pets idosos', image: '../../assets/img/carrinho.png' },
    { id: 'p27', name: 'Bebedouro Automático', price: '125.90', desc: 'Fonte de água com filtro 2L', image: '../../assets/img/carrinho.png' },
    { id: 'p28', name: 'Arranhador Gatos', price: '89.90', desc: 'Torre arranhador com brinquedos', image: '../../assets/img/carrinho.png' },
    { id: 'p29', name: 'Ração Coelho', price: '35.90', desc: 'Pellets nutritivos para coelhos 1kg', image: '../../assets/img/carrinho.png' },
    { id: 'p30', name: 'Kit Higiene', price: '52.90', desc: 'Shampoo, condicionador e perfume', image: '../../assets/img/carrinho.png' }
  ],
   mercearia: [
  { id: 'm1', name: 'MAIONESE HEALMANNS SCH 200G', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm2', name: 'MARGARINA QUALY 500G', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm3', name: 'MARGARINA QUALY 250G', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm4', name: 'MARGARINA PURO SABOR 500G', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm5', name: 'MARGARINA PURO SABOR 250G', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm6', name: 'MASSA PRA TAPIOCA PRECIOSO 1KG', price: '1', desc: '10 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm7', name: 'MILHO DE PIPOCA YOKI 400G', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm8', name: 'MILHO VERDE SCH 170G FUGINI', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm9', name: 'MOLHO DE TOMATE FUGINI 300G TRADICIONAL SCH', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm10', name: 'MUCILON 180G SCH ARROZ E AVEIA', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm11', name: 'MUCILON 180G SCH MILHO', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm12', name: 'MULTIUSO ORIGINAL VEJA AZUL', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm13', name: 'OLEO SOYA 900ML', price: '1', desc: '20 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm14', name: 'PALITO GINA ', price: '1', desc: '100 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm15', name: 'PAPEL ALUMINIO TERMICA 7,5 X 30CM', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm16', name: 'PAPEL HIGIENICO FLORAL NEUTRO', price: '1', desc: '16 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm17', name: 'PAPEL HIGIENICO MIMMO NEUTRO', price: '1', desc: '16 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm18', name: 'PAPEL TOALHA ESCALA', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm19', name: 'POLIDOR LIMPA FACIL TRADICIONAL 500ML', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm20', name: 'REFRESCO TANG 18G MARACUJA', price: '1', desc: '24 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm21', name: 'REFRESCO TANG 18G LIMAO', price: '1', desc: '24 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm22', name: 'REFRESCO TANG 18G UVA', price: '1', desc: '24 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm23', name: 'REFRESCO TANG 18G MORANGO', price: '1', desc: '24 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm24', name: 'REFRI GUARANA ANTARTICA 1L', price: '2', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm25', name: 'REFRI GUARANA ANTARTICA 200ML', price: '2', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm26', name: 'COCA COLA 1L', price: '4', desc: '6 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm27', name: 'COCA COLA ZERO 1L', price: '4', desc: '6 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm28', name: 'COCA COLA 250ML PET', price: '3', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm29', name: 'COCA COLA ZERO 250ML PET', price: '3', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm30', name: 'COCA COLA 2L', price: '4', desc: '6 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm31', name: 'COCA COLA ZERO 2L', price: '4', desc: '6 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm32', name: 'COCA COLA LATA 350ML', price: '4', desc: '6 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm33', name: 'COCA COLA ZERO LATA 350ML', price: '4', desc: '6 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm34', name: 'REFRI FANTA LARANJA 250ML', price: '2', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm35', name: 'REFRI FANTA LARANJA 2L', price: '4', desc: '6 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm36', name: 'REFRI FANTA UVA 250ML', price: '2', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm37', name: 'REFRI FANTA UVA 2L', price: '4', desc: '6 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm38', name: 'REFRI FANTA LARANJA LT 350ML', price: '4', desc: '6 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm39', name: 'REFRI FANTA UVA LT 350ML', price: '4', desc: '6 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm40', name: 'REFRI SAO GERALDO 1L', price: '4', desc: '6 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm41', name: 'REFRI SAO GERALDO 2L', price: '4', desc: '6 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm42', name: 'REFRI SAO GERALDO 350ML', price: '2', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm43', name: 'REFRI SAO GERALDO 350ML ZERO', price: '2', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm44', name: 'REFRI SPRITE 350ML', price: '4', desc: '6 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm45', name: 'SAB EVEN 85G LAVANDA', price: '1', desc: '24 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm46', name: 'SAB EVEN 85G BUQUE DE ROSAS', price: '1', desc: '24 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm47', name: 'SAB PROTEX MEN SPORTS 85G', price: '1', desc: '24 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm48', name: 'SAB PROTEX CREAM 85G', price: '1', desc: '24 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm49', name: 'SABAO EM BARRA YPE NEUTRO 5X160G', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm50', name: 'SABAO EM PO ALA 400G ROSAS E FLOR DE LIS', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm51', name: 'SABAO EM PO BRILHANTE 400G AZUL', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm52', name: 'SAL REFINADO ALTEZA 1KG', price: '1', desc: '20 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm53', name: 'SARDINHA COSTA GOMES AO MOLHO', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm54', name: 'SARDINHA COSTA GOMES EM OLEO', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm55', name: 'SHAMPOO CLEAR MEN 200ML LIMPEZA DIARIA 2EM1', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm56', name: 'SUCO KAPO 200ML LARANJA', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm57', name: 'SUCO KAPO 200ML UVA', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm58', name: 'TRIGO FINNA C FERMENTO', price: '1', desc: '10 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm59', name: 'TRIGO FINNA S FERMENTO', price: '1', desc: '10 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm60', name: 'VELA VIWACE N-10 128G', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm61', name: 'VINAGRE ALCOOL REGINA', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm62', name: 'ABS SEMPRE LIVRE NOTURNO', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm63', name: 'ABS INTIMUS SUAVE C ABAS', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm64', name: 'ABS INTIMUS SUAVE S ABAS', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm65', name: 'ABS SEMPRE LIVRE SUAVE C ABAS', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm66', name: 'ABS SEMPRE LIVRE SUAVE S ABAS', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm67', name: 'ABS INTIMUS NOTURNO', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm68', name: 'AÇUCAR PAYOL', price: '3', desc: '10 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm69', name: 'ADESIVO PEGA RATO', price: '1', desc: '25 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm70', name: 'AÇUCAR DEMERARA UNIAO', price: '1', desc: '10 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm71', name: 'ADOCANTE', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm72', name: 'AGUA INDAIA S GAS 1,5L', price: '1', desc: '6 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm73', name: 'AGUA INDAIA S GAS 500ML', price: '3', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm74', name: 'AGUA INDAIA C GAS 500ML', price: '3', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm75', name: 'AGUA SANITARIA BRILUX BRANCA 1L', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm76', name: 'AGUA SANITARIA DRAGAO 1L', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm77', name: 'ALCOOL SANTA CRUZ 1L 70%', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm78', name: 'ALGODAO NEVOA 25G', price: '1', desc: '20 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm79', name: 'TEMPEROS', price: '0', desc: '0 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm80', name: 'AMACIANTE DOWNY BRISA INTENSO 500ML', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm81', name: 'AMACIANTE SONHO 2L AZUL PROFUNDO', price: '2', desc: '6 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm82', name: 'MAIZENA 200G', price: '1', desc: '20 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm83', name: 'CERAIS', price: '0', desc: '0 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm84', name: 'ARROZ 101 BRANCO', price: '2', desc: '30 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm85', name: 'ARROZ 101 PARBORIZADO', price: '2', desc: '30 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm86', name: ' ARROZ ITAGUARY BRANCO', price: '2', desc: '30 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm87', name: 'ARROZ ITAGUARY PARBORIZADO', price: '2', desc: '30 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm88', name: 'AVEIA FLOCOS FINOS QUAKER', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm89', name: 'TAMPICO 330ML', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm90', name: 'CREAM CRACKER FORTALEZA 350G', price: '1', desc: '24 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm91', name: 'BISC MAIZENA 350G', price: '1', desc: '24 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm92', name: 'BISC FORTALEZA POP SALGADA', price: '1', desc: '20 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm93', name: 'BISC RECHEADO ANIMADOS QUADRADO 130G CHOC', price: '1', desc: '20 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm94', name: 'BISC RECHEADO ANIMADOS QUADRADO 130G MORANGO', price: '1', desc: '20 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm95', name: 'BISC RECH PIRAQUE DOCE DE LEITE', price: '1', desc: '20 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm96', name: 'BISC RECH AMORI PACK CHOC 125G', price: '1', desc: '20 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm97', name: 'BISC RECH AMORI PACK MORANGO 125G', price: '1', desc: '20 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm98', name: 'BISC RECH AMORI ESCURETO 125G', price: '1', desc: '20 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm99', name: 'BISC ROSQUINHA FORTALEZA CHOC', price: '1', desc: '24 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm100', name: 'BISC ROSQUINHA FORTALEZA COCO', price: '1', desc: '24 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm101', name: 'CAFE SANTA CLARA CLASSIC 100G ', price: '1', desc: '20 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm102', name: 'CAFE SANTA CLARA CLASSIC 250G VACUO', price: '1', desc: '20 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm103', name: 'COCO RALADO MENINA 50G ', price: '1', desc: '20 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm104', name: 'COLORIFICO DONA CLARA 100G', price: '1', desc: '20 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm105', name: 'ACETONA ALYNE 100ML', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm106', name: 'GILLETE PRESTOBARBA', price: '1', desc: '20 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm107', name: 'CANETA AZUL BIC', price: '1', desc: '1 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm108', name: 'CALDO MAGGI 57G GALINHA', price: '1', desc: '20 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm109', name: 'CALDO MAGGI 57G CARNE', price: '1', desc: '20 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm110', name: 'COLA MALUCA 2G', price: '1', desc: '20 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm111', name: 'CR DENT COLGATE TRIPLA AÇÃO 90G', price: '1', desc: '20 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm112', name: 'CR DENT COLGATE MPA 90G', price: '1', desc: '20 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm113', name: 'CR DENT SORRISO 50G', price: '1', desc: '20 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm114', name: 'ALHO ROXO NACIONAL KG', price: '1', desc: '4 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm115', name: 'CREME DE LEITE BETANIA 200G', price: '1', desc: '27 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm116', name: 'CURATIVO', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm117', name: 'DES. DOVE FEMININO ORIGINAL 150ML', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm118', name: 'DES. REXONA FEM POWDER 150ML', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm119', name: 'DES. REXONA MASC ACTIVE DRY 150ML', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm120', name: 'DESINFETANTE BAK YPE FLORAL', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm121', name: 'DESINFETANTE BAK YPE LAVANDA', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm122', name: 'DESINFETANTE MEU LAR 1L OCEANIC', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm123', name: 'DESINFETANTE MEU LAR 1L NATURE', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm124', name: 'DETERGENTE YPE NEUTRO', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm125', name: 'DETERGENTE YPE COCO', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm126', name: 'DETERGENTE YPE MAÇA', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm127', name: 'DUETO FUGINI 170G', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm128', name: 'ERVILHA FUGINI 170G', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm129', name: 'ESCOVA ORAL B 123', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm130', name: 'ESCOVA INFANTIL', price: '0', desc: '0 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm131', name: 'ESCOVAO PLASTICO ANATOMICA', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm132', name: 'ESPONJA BRILHUS', price: '1', desc: '60 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm133', name: 'ESPETILHO P CHURRASCO 30CM', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm134', name: 'ESPONJA DE AÇO ASSOLAN', price: '1', desc: '24 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm135', name: 'EXTRATO DE TOMATE FUGINI 300G', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm136', name: 'FARINHA AMARELA PONTO DO FEIJAO', price: '1', desc: '10 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm137', name: 'FAROFA PRONTA YOKI 200G ', price: '1', desc: '14 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm138', name: 'FECULA JURITI 1KG', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm139', name: 'FEIJAO CARIOCA PONTO DO FEIJAO', price: '1', desc: '10 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm140', name: 'FEIJAO CORDA PONTO DO FEIJAO', price: '1', desc: '10 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm141', name: 'FEIJAO PRETO PONTO DO FEIJAO', price: '1', desc: '10 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm142', name: 'FREMENTO QUIM DONA BENTA 100G', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm143', name: 'FILME PVC BOMPACK 28X15', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm144', name: 'FLOCAO DONA CLARA 500G', price: '1', desc: '30 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm145', name: 'FOSFOROS ARGOS', price: '1', desc: '20 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm146', name: 'GUARDANAPOS SCALA', price: '1', desc: '20 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm147', name: 'HASTES FLEXIVEIS COTTON LINE', price: '1', desc: '20 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm148', name: 'BAYGON ', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm149', name: 'ISQUEIRO BIC MAXI', price: '1', desc: '20 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm150', name: 'NISSIN GALINHA CAIPIRA', price: '1', desc: '24 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm151', name: 'LAMEN NOSSO CARNE', price: '1', desc: '24 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm152', name: 'LAVA R. LIQ. OMO 700ML', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm153', name: 'LAVA R. LIQ. TIXAN 700ML', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm154', name: 'LEITE CONDENSADO BETANIA', price: '1', desc: '27 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm155', name: 'LEITE DE COCO MENINA 200ML', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm156', name: 'LEITE EM PO INTEGRAL ITAMBE 200G', price: '1', desc: '20 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm157', name: 'LEITE EM PO DESNATADO ITAMBE 200G', price: '1', desc: '20 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm158', name: 'LEITE CX BETANIA INTEGRAL 1L', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm159', name: 'LEITE CX DESNATADO INTEGRAL 1L', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm160', name: 'MACARRAO ESPAGUETE FORTALEZA 400G', price: '1', desc: '14 unidades', image: '../../assets/img/carrinho.png' },
  { id: 'm161', name: 'MACARRAO LASANHA ESTRELA SEMOLA 500G', price: '1', desc: '12 unidades', image: '../../assets/img/carrinho.png' },
  ],
  lanches: [
    { id: 'l1', name: 'Hambúrguer Artesanal', price: '15.90', desc: 'Hambúrguer 180g com queijo e bacon', image: '../../assets/img/carrinho.png' },
    { id: 'l2', name: 'Hot Dog Completo', price: '12.90', desc: 'Hot dog com batata palha e molhos', image: '../../assets/img/carrinho.png' },
    { id: 'l3', name: 'Sanduíche Natural', price: '8.90', desc: 'Sanduíche integral com peito de peru', image: '../../assets/img/carrinho.png' },
    { id: 'l4', name: 'Coxinha de Frango', price: '4.50', desc: 'Coxinha tradicional frita na hora', image: '../../assets/img/carrinho.png' },
    { id: 'l5', name: 'Pastel de Queijo', price: '5.90', desc: 'Pastel assado com queijo derretido', image: '../../assets/img/carrinho.png' },
    { id: 'l6', name: 'Pão de Açúcar', price: '3.50', desc: 'Pão doce tradicional', image: '../../assets/img/carrinho.png' },
    { id: 'l7', name: 'Empada de Palmito', price: '6.90', desc: 'Empada assada com palmito', image: '../../assets/img/carrinho.png' },
    { id: 'l8', name: 'Esfirra de Carne', price: '4.90', desc: 'Esfirra aberta com carne temperada', image: '../../assets/img/carrinho.png' },
    { id: 'l9', name: 'Pizza Fatia', price: '7.90', desc: 'Fatia de pizza margherita', image: '../../assets/img/carrinho.png' },
    { id: 'l10', name: 'Açaí 300ml', price: '9.90', desc: 'Açaí cremoso com granola', image: '../../assets/img/carrinho.png' },
    { id: 'l11', name: 'Vitamina de Banana', price: '6.50', desc: 'Vitamina natural com leite', image: '../../assets/img/carrinho.png' },
    { id: 'l12', name: 'Suco de Laranja', price: '5.90', desc: 'Suco natural 300ml', image: '../../assets/img/carrinho.png' },
    { id: 'l13', name: 'Café Expresso', price: '3.50', desc: 'Café expresso tradicional', image: '../../assets/img/carrinho.png' },
    { id: 'l14', name: 'Cappuccino', price: '5.90', desc: 'Cappuccino cremoso com canela', image: '../../assets/img/carrinho.png' },
    { id: 'l15', name: 'Chocolate Quente', price: '6.90', desc: 'Chocolate quente com marshmallow', image: '../../assets/img/carrinho.png' },
    { id: 'l16', name: 'Bolo de Cenoura', price: '4.90', desc: 'Fatia de bolo com cobertura', image: '../../assets/img/carrinho.png' },
    { id: 'l17', name: 'Pudim de Leite', price: '5.50', desc: 'Pudim caseiro individual', image: '../../assets/img/carrinho.png' },
    { id: 'l18', name: 'Brigadeiro Gourmet', price: '3.90', desc: 'Brigadeiro artesanal', image: '../../assets/img/carrinho.png' },
    { id: 'l19', name: 'Beijinho de Coco', price: '3.90', desc: 'Doce de coco tradicional', image: '../../assets/img/carrinho.png' },
    { id: 'l20', name: 'Torta de Limão', price: '6.90', desc: 'Fatia de torta com merengue', image: '../../assets/img/carrinho.png' },
    { id: 'l21', name: 'Croissant Presunto', price: '7.90', desc: 'Croissant com presunto e queijo', image: '../../assets/img/carrinho.png' },
    { id: 'l22', name: 'Misto Quente', price: '6.50', desc: 'Sanduíche quente tradicional', image: '../../assets/img/carrinho.png' },
    { id: 'l23', name: 'Bauru Completo', price: '11.90', desc: 'Bauru com rosbife e queijo', image: '../../assets/img/carrinho.png' },
    { id: 'l24', name: 'Wrap de Frango', price: '9.90', desc: 'Wrap integral com frango grelhado', image: '../../assets/img/carrinho.png' },
    { id: 'l25', name: 'Salada Caesar', price: '12.90', desc: 'Salada com frango e molho caesar', image: '../../assets/img/carrinho.png' },
    { id: 'l26', name: 'Quiche Lorraine', price: '8.90', desc: 'Quiche com bacon e queijo', image: '../../assets/img/carrinho.png' },
    { id: 'l27', name: 'Crepe Doce', price: '7.90', desc: 'Crepe com doce de leite', image: '../../assets/img/carrinho.png' },
    { id: 'l28', name: 'Crepe Salgado', price: '9.90', desc: 'Crepe com frango e catupiry', image: '../../assets/img/carrinho.png' },
    { id: 'l29', name: 'Milkshake Morango', price: '8.90', desc: 'Milkshake cremoso 400ml', image: '../../assets/img/carrinho.png' },
    { id: 'l30', name: 'Smoothie Verde', price: '9.90', desc: 'Smoothie detox com frutas', image: '../../assets/img/carrinho.png' }
  ], image: '../../assets/img/carrinho.png'
};
